name: CI Release

on: 
  push:
    branches:
    - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy Release
      run: sh ./deploy.sh
